import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { getRole, clearRole } from "../utils/role";

const apiBaseUrl = import.meta.env.VITE_API_URL || "http://localhost:3000";

export default function NursePage() {
  const [queue, setQueue] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [actionError, setActionError] = useState("");
  const [actionBusyId, setActionBusyId] = useState(null);
  const navigate = useNavigate();

  const loadQueue = async () => {
    try {
      const response = await fetch(`${apiBaseUrl}/tickets/queue`);
      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.message || "Unable to load queue");
      }

      setQueue(data.queue || []);
    } catch (err) {
      setError(err.message || "Load failed");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadQueue();
  }, []);

  const runAction = async (ticketId, action) => {
    try {
      setActionError("");
      setActionBusyId(ticketId);

      const response = await fetch(
        `${apiBaseUrl}/tickets/${ticketId}/${action}`,
        {
          method: "POST",
        },
      );

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.message || `Failed to ${action} ticket`);
      }

      await loadQueue();
    } catch (err) {
      setActionError(err.message || "Action failed");
    } finally {
      setActionBusyId(null);
    }
  };

  return (
    <main
      style={{
        minHeight: "100vh",
        background: "#f8fafc",
        color: "#0f172a",
        fontFamily: "Arial, sans-serif",
        padding: "32px 16px",
      }}
    >
      <div style={{ maxWidth: 980, margin: "0 auto" }}>
        <div
          style={{
            marginBottom: 24,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            gap: 12,
            flexWrap: "wrap",
          }}
        >
          <div>
            <div
              style={{
                display: "inline-block",
                background: "#dbeafe",
                borderRadius: 999,
                padding: "8px 16px",
                fontSize: 12,
                fontWeight: 700,
                letterSpacing: 1,
                textTransform: "uppercase",
                color: "#1d4ed8",
              }}
            >
              Nurse View
            </div>
            <h1
              style={{
                margin: "16px 0 0",
                fontSize: "clamp(2rem, 4vw, 3rem)",
                lineHeight: 1.1,
              }}
            >
              Patient Registration Desk
            </h1>
          </div>

          <nav style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
            <Link to="/" style={navStyle}>
              Home
            </Link>
            {getRole() === "nurse" ? (
              <>
                <Link to="/nurse" style={navStyle}>
                  Nurse
                </Link>
                <button
                  onClick={() => {
                    clearRole();
                    navigate("/");
                  }}
                  style={navStyle}
                >
                  Change Role
                </button>
              </>
            ) : (
              <Link to="/nurse" style={navStyle}>
                Nurse
              </Link>
            )}
          </nav>
        </div>

        <section
          style={{
            background: "#ffffff",
            borderRadius: 18,
            padding: 28,
            border: "1px solid #dfe3e8",
            boxShadow: "0 8px 24px rgba(15, 23, 42, 0.05)",
          }}
        >
          <h2 style={{ marginTop: 0, marginBottom: 12 }}>
            Nurse responsibilities
          </h2>
          <ul
            style={{
              fontSize: 18,
              lineHeight: 1.8,
              paddingLeft: 24,
              margin: 0,
            }}
          >
            <li>Register incoming patients quickly and accurately.</li>
            <li>Capture language preference, phone, and visual identifier.</li>
            <li>Use the queue numbering generated by the backend sequence.</li>
            <li>
              Keep the system safe against duplicate registration retries.
            </li>
            <li>Hold patients when needed and recall them back into queue.</li>
          </ul>
        </section>

        {actionError && (
          <div style={{ marginTop: 16, color: "#b42318", fontWeight: 700 }}>
            {actionError}
          </div>
        )}

        <section
          style={{
            background: "#ffffff",
            borderRadius: 18,
            padding: 28,
            border: "1px solid #dfe3e8",
            boxShadow: "0 8px 24px rgba(15, 23, 42, 0.05)",
            marginTop: 24,
          }}
        >
          <h2 style={{ marginTop: 0, marginBottom: 16 }}>Current queue</h2>

          {loading ? (
            <p>Loading queue…</p>
          ) : error ? (
            <p style={{ color: "#b42318" }}>{error}</p>
          ) : queue.length === 0 ? (
            <p>No patients in the active queue.</p>
          ) : (
            <div style={{ display: "grid", gap: 12 }}>
              {queue.map((ticket) => (
                <div
                  key={ticket.id}
                  style={{
                    border: "1px solid #e5e7eb",
                    borderRadius: 12,
                    padding: 14,
                    display: "grid",
                    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
                    gap: 12,
                    background: "#f9fafb",
                    alignItems: "center",
                  }}
                >
                  <div>
                    <div style={{ fontSize: 12, color: "#6b7280" }}>Queue</div>
                    <strong>{ticket.queuePosition}</strong>
                  </div>
                  <div>
                    <div style={{ fontSize: 12, color: "#6b7280" }}>Ticket</div>
                    <strong>{ticket.sequence_number}</strong>
                  </div>
                  <div>
                    <div style={{ fontSize: 12, color: "#6b7280" }}>
                      Patient
                    </div>
                    <strong>{ticket.displayName}</strong>
                  </div>
                  <div>
                    <div style={{ fontSize: 12, color: "#6b7280" }}>Status</div>
                    <strong>{ticket.status}</strong>
                  </div>
                  <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                    <button
                      className="btn"
                      onClick={() => runAction(ticket.id, "hold")}
                      disabled={actionBusyId === ticket.id}
                    >
                      Hold
                    </button>
                    <button
                      className="btn btn-outline"
                      onClick={() => runAction(ticket.id, "recall")}
                      disabled={actionBusyId === ticket.id}
                    >
                      Recall
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>
    </main>
  );
}

const navStyle = {
  textDecoration: "none",
  color: "#111827",
  background: "#ffffff",
  border: "1px solid #d1d5db",
  borderRadius: 999,
  padding: "8px 14px",
  fontWeight: 700,
};
